name: 'batch-a-build'
on:
  push:
    branches:
      - main
    paths:
      - 'src/batch-a/**'
  workflow_dispatch:
jobs:
  batch_a_build:
    runs-on: ubuntu-latest
    name: A job to build go batch a
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v3
        with:
          go-version: '^1.20.1'
      - id: build
        uses: ./.github/actions/build
        with:
          entrypoint: './batch-a'
          working-directory: './src'
